const translate = {
    "ar": {
        "Home": "الرئيسية",
        "About": "معلومات",
        "Articles": "مقالات",
        "FAQ": "الأسئلة الشائعة",
        "FAQTitle": "الأسئلة الشائعة",
        "Videos": "فيديوهات",
        "Schedule a Call": "جدولة مكالمة",
        "Watch Videos": "شاهد فيديوهات",
        "onlineConsultation": "التواصل",
        "innovativeMedicine": "الطب المتطور",
        "watchVideos": "شاهد الفيديوهات",
        "videos": "فيديوهات",
        "scheduleACall": "جدولة مكالمة",
        "copyright": "2025 مدعوم بواسطة",
        "NoVideos": "لا توجد فيديوهات",
        "Testimonials": "آراء العملاء",
        "Useless": "غير مفيد",
        "Useless+": "غير مفيد+",
        "Poor": "سيء",
        "Poor+": "سيء+",
        "Ok": "مقبول",
        "Ok+": "مقبول+",
        "Good": "جيد",
        "Good+": "جيد+",
        "Excellent": "ممتاز",
        "Excellent+": "ممتاز+",
        "Name": "الاسم",
        "ِEmail": "البريد الإلكتروني",
        "YourComment": "تعليقك",
        "Phone": "الهاتف",
        "WriteYourOpinion": "اكتب تعليقك وقم بتقييم الطبيب",
        "Save": "حفظ",
        "ThisFieldIsRequired": "هذا الحقل مطلوب",
        "TestimonialAddedSuccessfully": "تم إضافة الآراء بنجاح وسيتم تحقيقه قريبا",
        "WeCareAboutYourOpinion": "نحن نقدّر رأيك",
        "ShareYourThoughtsAndHelpOthers": "اخبرنا عن تجربتك وساعد المرضى الآخرين بتقييم الطبيب.",
        "WriteYourReviewAndRateTheDoctor": "اكتب تعليقك وقم بتقييم الطبيب",
        "DuplicateTestimonial": "لقد قمت بإرسال آراء بنفس البريد الإلكتروني أو رقم الهاتف من قبل",
    },
    "en": {
        "Home": "Home",
        "About": "About",
        "Articles": "Articles",
        "FAQ": "FAQ",
        "FAQTitle": "Frequently Asked Questions",
        "Videos": "Videos",
        "Watch Videos": "Watch Videos",
        "onlineConsultation": "Contact",
        "innovativeMedicine": "Innovative Medicine",
        "watchVideos": "Watch Videos",
        "videos": "Videos",
        "scheduleACall": "Schedule a Call",
        "copyright": "2025 Powered By",
        "NoVideos": "No Videos Available",
        "Testimonials": "Testimonials",
        "Useless": "Useless",
        "Useless+": "Useless+",
        "Poor": "Poor",
        "Poor+": "Poor+",
        "Ok": "Ok",
        "Ok+": "Ok+",
        "Good": "Good",
        "Good+": "Good+",
        "Excellent": "Excellent",
        "Excellent+": "Excellent+",
        "Name": "Name",
        "ِEmail": "Email",
        "YourComment": "Your Comment",
        "Phone": "Phone",
        "WriteYourOpinion": "Write Your Opinion & Rate the Doctor",
        "Save": "Save",
        "ThisFieldIsRequired": "This field is required",
        "TestimonialAddedSuccessfully": "Testimonial added successfully and will be reviewed shortly",
        "WeCareAboutYourOpinion": "We Care About Your Opinion",
        "ShareYourThoughtsAndHelpOthers": "Share Your Thoughts and Help Others",
        "WriteYourReviewAndRateTheDoctor": "Write Your Review & Rate the Doctor",
        "DuplicateTestimonial": "You have already submitted a testimonial with this email or phone number",
    },
};

export default translate;